In [1]:
import torch

In [5]:
A = torch.tensor([[1,1], [2,1], [0,2]])
A

tensor([[1, 1],
        [2, 1],
        [0, 2]])

In [6]:
A.t()

tensor([[1, 2, 0],
        [1, 1, 2]])

In [8]:
dot = torch.matmul(A, A.t())
dot

tensor([[2, 3, 2],
        [3, 5, 2],
        [2, 2, 4]])

In [10]:
square_norm = torch.diag(dot)
square_norm

tensor([2, 5, 4])

In [15]:
square_norm.unsqueeze(0) - 2 * dot + square_norm.unsqueeze(1)

tensor([[0, 1, 2],
        [1, 0, 5],
        [2, 5, 0]])